# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

constant_funC <- function(W, K) {
    .Call('_lnmCluster_constant_funC', PACKAGE = 'lnmCluster', W, K)
}

